New feature: direct WebUI access to Slave thru Master

diff --git a/bin/vigrid-addslave b/bin/vigrid-addslave
--- a/bin/vigrid-addslave
+++ b/bin/vigrid-addslave
@@ -125,7 +125,7 @@ done
 
 echo "Please:
   - Ensure traffic from this host to GNS3 & SSH ports of host $SLAVE_HOST are open and working fine.
-  - Find the password of the 'gns3' user of host $SLAVE_HOST, it will be required later.
+  - Ensure about the password of the 'gns3' user of host $SLAVE_HOST, it will be required later.
 
 Press [RETURN] when ready."
 read ANS
@@ -143,7 +143,7 @@ else
 fi
 
 echo "  Updating Vigrid API translation table $VIGRID_TRANSLATION_TABLE..."
-[ -f $VIGRID_TRANSLATION_TABLE ] && touch $VIGRID_TRANSLATION_TABLE
+[ ! -f $VIGRID_TRANSLATION_TABLE ] && touch $VIGRID_TRANSLATION_TABLE
 
 CHK=`cat $VIGRID_TRANSLATION_TABLE 2>/dev/null | egrep "^$SLAVE_IP:$SLAVE_PORT=https://$SLAVE_FQDN"`
 if [ "x$CHK" = "x" ]
@@ -151,225 +151,30 @@ then
   CHK=`cat $VIGRID_TRANSLATION_TABLE 2>/dev/null | egrep "^$SLAVE_IP:$SLAVE_PORT="`
   if [ "x$CHK" != "x" ]
   then
-    echo "    WARNING !! There is already a translation for $SLAVE_IP:$SLAVE_PORT:"
+    echo "    Translation already exists for $SLAVE_IP:$SLAVE_PORT:"
     cat $VIGRID_TRANSLATION_TABLE 2>/dev/null | egrep "^$SLAVE_IP:$SLAVE_PORT=" | sed 's/^/    /g'
   else
     echo "$SLAVE_IP:$SLAVE_PORT=https://$SLAVE_FQDN" >>$VIGRID_TRANSLATION_TABLE
   fi
 else
-  echo "    Warning, $SLAVE_IP:$SLAVE_PORT=https://$SLAVE_FQDN already exists"
+    echo "    Translation already exists for $SLAVE_IP:$SLAVE_PORT:https://$SLAVE_FQDN"
 fi
 
-echo "  Checking & updating OpenResty virtual hosts..."
-NGINX_CONFIG="
-#
-# Vigrid HTTPS access for Slave %%SLAVE_HOST%% (%%SLAVE_FQDN%%), %%SLAVE_IP%%:%%SLAVE_PORT%%
-#
-server {
-  listen 127.0.0.1:443 ssl;
-  server_name %%SLAVE_HOST%% %%SLAVE_FQDN%%;
+echo "  Adding Virtual Host for $SLAVE_HOST on OpenResty..."
+NGINX_SLAVE_CONFIG="/etc/nginx/sites/CyberRange-443-$SLAVE_HOST.conf"
 
-  # Take fullchain here, not cert.pem
-  ssl_certificate      /etc/nginx/ssl/localhost.crt;
-  ssl_certificate_key  /etc/nginx/ssl/localhost.key;
+if [ -f $NGINX_SLAVE_CONFIG ]
+then
+  echo "/etc/nginx/sites/CyberRange-443-$SLAVE_HOST.conf already exists, skipping"
+else
+  cp /home/gns3/vigrid/confs/nginx/vigrid-www-https-for_slave.conf $NGINX_SLAVE_CONFIG
+  [ $? -ne 0 ] && Error 'Creating $NGINX_SLAVE_CONFIG from vigrid-www-https-for_slave.conf template failed'
 
-  ssl_session_cache    builtin:1000 shared:SSL:1m;
-  ssl_session_timeout  5m;
-
-  ssl_protocols   TLSv1.2 TLSv1.3;
-  ssl_ciphers  HIGH:!aNULL:!MD5;
-  ssl_prefer_server_ciphers  on;
-
-  # hide version
-  server_tokens        off;
-
-  access_log /var/log/nginx/access.log;
-  error_log /var/log/nginx/error.log;
-
-  # Vigrid API, load only
-  location ~ ^/vigrid-api/.*\$
-  {
-    auth_request     /auth;
-    auth_request_set \$auth_status \$upstream_status;
-    auth_request_set \$auth_header \$upstream_http_authorization;
-
-    try_files \$uri /vigrid-api/vigrid-api.html?order=\$is_args\$args;
-    fastcgi_split_path_info       ^/(.+\/vigrid-api)(/.+)\$;
-    fastcgi_pass                  unix:/run/php/php$PHP_VER-fpm.sock;
-    # Minimum output buffering
-    fastcgi_buffers               2 4k;
-    fastcgi_busy_buffers_size     4k;
-    fastcgi_buffering             off;
-    # fastcgi_buffer_size           8k; 
-    include                       /etc/nginx/fastcgi_params;
-    fastcgi_read_timeout          300;
-    fastcgi_param PATH_INFO       \$fastcgi_path_info;
-    fastcgi_param HTTP_AUTHORIZATION \$http_authorization;
-    fastcgi_param SCRIPT_FILENAME \$document_root/vigrid-api/vigrid-api.html?order=\$1;
-  }
-  
-  # GNS Heavy client
-  location ^~ /v2
-  {
-    auth_request_set \$auth_status \$upstream_status;
-    auth_request_set \$auth_header \$upstream_http_authorization;
-
-    proxy_set_header Host \$host;
-
-    proxy_http_version 1.1;
-    proxy_set_header Upgrade \$http_upgrade;
-    proxy_set_header Connection 'Upgrade';
-
-    access_by_lua_block
-    {
-      if ngx.var.http_authorization ~= nil and ngx.var.http_authorization:sub(0, 6) == 'Basic ' then
-
-        -- Extract Basic auth
-        auth_creds=string.gsub(ngx.var.http_authorization,'^Basic ','',1)
-        local vigrid_creds = ngx.decode_base64(auth_creds)
-
-        -- Splitting credentials
-        local vigrid_user=string.gsub(vigrid_creds,':.*\$','',1)
-        local vigrid_pass=string.gsub(vigrid_creds,'^.*:','',1)
-        if vigrid_user == '' or vigrid_pass == '' then
-          ngx.log(ngx.ERR, 'Unknown Vigrid credentials (', vigrid_creds, ') not granted to pass')
-          ngx.exit(401)
-          return
-        end
-
-        -- Check user is granted to pass
-        local grep_str=string.format(\"egrep '^%s:{PLAIN}%s\$' /home/gns3/etc/vigrid-passwd\",vigrid_user,vigrid_pass)
-        local p = io.popen(grep_str)
-        local vigrid_check = p:read('*l')
-        p:close()
-        
-        if vigrid_check == nil then
-          ngx.log(ngx.ERR, 'Unknown Vigrid credentials (', vigrid_creds, ') not granted to pass')
-          ngx.exit(401)
-          return
-        end
-
-        -- Yes ? Extract user/pass from gns3_server.conf
-        local p = io.popen(\"egrep '^(user|password)\\\\\\s*=' /home/gns3/.config/GNS3/gns3_server.conf\")
-        local res_user = p:read('*l')
-        local res_pass = p:read('*l')
-        p:close()
-        gns_user=string.gsub(res_user,'^user[ ]+=[ ]+','',1)
-        gns_pass=string.gsub(res_pass,'^password[ ]+=[ ]+','',1)
-
-        -- Build base64 header
-        local basic = string.format('%s:%s',gns_user,gns_pass)
-        local basicb64 = ngx.encode_base64(basic,false)
-
-        -- Replace authorization
-        authorization = string.format('Basic %s',basicb64)
-        ngx.req.set_header('Authorization', authorization)
-
-        return
-      end
-    }
-
-    proxy_pass http://%%SLAVE_IP%%:3080;
-  }
-
-  # GNS WebUI client
-  location ^~ /static
-  {
-    auth_request_set \$auth_status \$upstream_status;
-    auth_request_set \$auth_header \$upstream_http_authorization;
-
-    proxy_set_header Host \$host;
-
-    proxy_http_version 1.1;
-    proxy_set_header Upgrade \$http_upgrade;
-    proxy_set_header Connection 'Upgrade';
-
-    access_by_lua_block
-    {
-      if ngx.var.http_authorization ~= nil and ngx.var.http_authorization:sub(0, 6) == 'Basic ' then
-
-        -- Extract Basic auth
-        auth_creds=string.gsub(ngx.var.http_authorization,'^Basic ','',1)
-        local vigrid_creds = ngx.decode_base64(auth_creds)
-
-        -- Splitting credentials
-        local vigrid_user=string.gsub(vigrid_creds,':.*\$','',1)
-        local vigrid_pass=string.gsub(vigrid_creds,'^.*:','',1)
-        if vigrid_user == '' or vigrid_pass == '' then
-          ngx.log(ngx.ERR, 'Unknown Vigrid credentials (', vigrid_creds, ') not granted to pass')
-          ngx.exit(401)
-          return
-        end
-
-        -- Check user is granted to pass
-        local grep_str=string.format(\"egrep '^%s:{PLAIN}%s\$' /home/gns3/etc/vigrid-passwd\",vigrid_user,vigrid_pass)
-        local p = io.popen(grep_str)
-        local vigrid_check = p:read('*l')
-        p:close()
-        
-        if vigrid_check == nil then
-          ngx.log(ngx.ERR, 'Unknown Vigrid credentials (', vigrid_creds, ') not granted to pass')
-          ngx.exit(401)
-          return
-        end
-
-        -- Yes ? Extract user/pass from gns3_server.conf
-        local p = io.popen(\"egrep '^(user|password)\\\\\\s*=' /home/gns3/.config/GNS3/gns3_server.conf\")
-        local res_user = p:read('*l')
-        local res_pass = p:read('*l')
-        p:close()
-        gns_user=string.gsub(res_user,'^user[ ]+=[ ]+','',1)
-        gns_pass=string.gsub(res_pass,'^password[ ]+=[ ]+','',1)
-
-        -- Build base64 header
-        local basic = string.format('%s:%s',gns_user,gns_pass)
-        local basicb64 = ngx.encode_base64(basic,false)
-
-        -- Replace authorization
-        authorization = string.format('Basic %s',basicb64)
-        ngx.req.set_header('Authorization', authorization)
-
-        return
-      end
-    }
-
-    proxy_pass http://%%SLAVE_IP%%:3080;
-  } 
-  
-  location = /auth
-  {
-    internal;
-    
-    proxy_pass             http://localhost:8001;
-    proxy_pass_request_body off;
-    
-    proxy_set_header        Content-Length \"\";
-    proxy_set_header        X-Original-URI \$request_uri;
-    proxy_set_header        X-Original-Host \$host;
-    proxy_set_header        X-Real-IP \$remote_addr;
-    proxy_set_header        X-Forwarded-For \$proxy_add_x_forwarded_for;
-    proxy_set_header        X-Forwarded-Host \$server_name;  
-  }
-}
-"
-
-for i in $VIGRID_GNS_SLAVE_HOSTS
-do
-  SLAVE_HOST=`echo $i|awk 'BEGIN {FS=":";} { print $1;}'`
-  SLAVE_IP=`echo $i|awk 'BEGIN {FS=":";} { print $2;}'`
-  SLAVE_PORT=`echo $i|awk 'BEGIN {FS=":";} { print $3;}'`
-  SLAVE_FQDN=`cat $VIGRID_TRANSLATION_TABLE 2>/dev/null | egrep "^$SLAVE_IP:$SLAVE_PORT="| awk -F '=' '{print $NF;}'`
-
-  NGINX_SLAVE_CONFIG="/etc/nginx/sites/CyberRange-$SLAVE_HOST-443.conf"
-
-  if [ ! -f $NGINX_SLAVE_CONFIG ]
-  then
-    echo "  $NGINX_SLAVE_CONFIG does not exist for %%SLAVE_HOST%% (%%SLAVE_FQDN%%), %%SLAVE_IP%%:%%SLAVE_PORT%%, creating it"
-
-    echo "$NGINX_CONFIG" | sed "s/%%SLAVE_HOST%%/$SLAVE_HOST/" | sed "s/%%SLAVE_IP%%/$SLAVE_IP/" \
-     | sed "s/%%SLAVE_PORT%%/$SLAVE_PORT/" | sed "s/%%SLAVE_FQDN%%/$SLAVE_FQDN/" >$NGINX_SLAVE_CONFIG
-  fi
-done
+  sed -i "s/%%SLAVE_HOST%%/$SLAVE_HOST/" $NGINX_SLAVE_CONFIG
+  sed -i "s/%%SLAVE_IP%%/$SLAVE_IP/" $NGINX_SLAVE_CONFIG
+  sed -i "s/%%SLAVE_PORT%%/$SLAVE_PORT/" $NGINX_SLAVE_CONFIG
+  sed -i "s/%%SLAVE_FQDN%%/$SLAVE_FQDN/" $NGINX_SLAVE_CONFIG
+fi
 
 echo -n "  Restarting OpenResty..."
 service openresty restart
@@ -379,7 +184,7 @@ then
   read CR
 fi
 
-echo "Adding slave SSH access"
+echo "Adding $SLAVE_HOST SSH access"
 /home/gns3/vigrid/bin/vigrid-sshcheck -a -s /home/gns3/etc/id_GNS3 -u gns3 -h $SLAVE_IP
 
 echo "Vigrid NAS actions:"
@@ -387,7 +192,13 @@ VIGRID_NAS_HOST=`echo $VIGRID_NAS_SERVER| awk 'BEGIN { FS=":"; } { print $1;}'`
 VIGRID_NAS_IP=`echo $VIGRID_NAS_SERVER| awk 'BEGIN { FS=":"; } { print $2;}'`
 
 echo "  Adding $SLAVE_HOST ($SLAVE_IP) host to /etc/hosts..."
-echo "$SLAVE_IP $SLAVE_HOST $SLAVE_HOST.GNS3" | ssh -i $VIGRID_SSHKEY_NAS $VIGRID_SSHKEY_OPTIONS root@$VIGRID_NAS_IP 'cat >>/etc/hosts'
+CHK=`ssh -i $VIGRID_SSHKEY_NAS $VIGRID_SSHKEY_OPTIONS root@$VIGRID_NAS_IP 'cat /etc/hosts'|grep "^$SLAVE_IP "`
+if [ "x$CHK" != "x" ]
+then
+  echo "$SLAVE_IP already defined in /etc/hosts, skipping"
+else
+  echo "$SLAVE_IP $SLAVE_HOST $SLAVE_FQDN" | ssh -i $VIGRID_SSHKEY_NAS $VIGRID_SSHKEY_OPTIONS root@$VIGRID_NAS_IP 'cat >>/etc/hosts'
+fi
 
 echo "Creating datasets for slave..."
 if [ "x$VIGRID_STORAGE_MODE" = "xZFS" ]
@@ -395,7 +206,6 @@ then
   ZFS_ROOT=`echo $VIGRID_STORAGE_ROOT|sed 's/^\///'`
   ssh -i $VIGRID_SSHKEY_NAS $VIGRID_SSHKEY_OPTIONS root@$VIGRID_NAS_IP "zfs create -p $ZFS_ROOT/NFS/$SLAVE_HOST/GNS3mount/GNS3/projects"
   ssh -i $VIGRID_SSHKEY_NAS $VIGRID_SSHKEY_OPTIONS root@$VIGRID_NAS_IP "zfs create -p $ZFS_ROOT/NFS/$SLAVE_HOST/var-lib-docker"
-
 fi
 
 if [ "x$VIGRID_STORAGE_MODE" = "xBTRfs" ]
@@ -407,17 +217,23 @@ then
 fi
 
 echo "  Adding Vigrid shares to /etc/exports..."
-echo "
-/Vstorage/NFS/$SLAVE_HOST/GNS3mount                $SLAVE_HOST.GNS3(rw,no_root_squash,no_subtree_check)
-/Vstorage/NFS/$SLAVE_HOST/GNS3mount/GNS3           $SLAVE_HOST.GNS3(rw,no_root_squash,no_subtree_check)
-/Vstorage/NFS/$SLAVE_HOST/GNS3mount/GNS3/projects  $SLAVE_HOST.GNS3(rw,no_root_squash,no_subtree_check)
-/Vstorage/NFS/$SLAVE_HOST/var-lib-docker           $SLAVE_HOST.GNS3(rw,no_root_squash,no_subtree_check)
-" | ssh -i $VIGRID_SSHKEY_NAS $VIGRID_SSHKEY_OPTIONS root@$VIGRID_NAS_IP 'cat >>/etc/exports'
+CHK=`ssh -i $VIGRID_SSHKEY_NAS $VIGRID_SSHKEY_OPTIONS root@$VIGRID_NAS_IP 'cat /etc/exports'| grep "\/$SLAVE_HOST\/"`
+if [ "x$CHK" != "x" ]
+then
+  echo "Exports already existing for $SLAVE_HOST, skipping"
+else
+  echo "
+  /Vstorage/NFS/$SLAVE_HOST/GNS3mount                $SLAVE_HOST.GNS3(rw,no_root_squash,no_subtree_check)
+  /Vstorage/NFS/$SLAVE_HOST/GNS3mount/GNS3           $SLAVE_HOST.GNS3(rw,no_root_squash,no_subtree_check)
+  /Vstorage/NFS/$SLAVE_HOST/GNS3mount/GNS3/projects  $SLAVE_HOST.GNS3(rw,no_root_squash,no_subtree_check)
+  /Vstorage/NFS/$SLAVE_HOST/var-lib-docker           $SLAVE_HOST.GNS3(rw,no_root_squash,no_subtree_check)
+  " | ssh -i $VIGRID_SSHKEY_NAS $VIGRID_SSHKEY_OPTIONS root@$VIGRID_NAS_IP 'cat >>/etc/exports'
 
-echo "  Now reloading NFS exports.. Sometimes this operation might fail because of discrepencies between datasets & exports".
-echo "  Press [RETURN] when you are ready to launch the action"
-read ANS
-ssh -i $VIGRID_SSHKEY_NAS $VIGRID_SSHKEY_OPTIONS root@$VIGRID_NAS_IP 'exportfs -a'
+  echo "  Now reloading NFS exports.. Sometimes this operation might fail because of discrepencies between datasets & exports".
+  echo "  Press [RETURN] when you are ready to launch the action"
+  read ANS
+  ssh -i $VIGRID_SSHKEY_NAS $VIGRID_SSHKEY_OPTIONS root@$VIGRID_NAS_IP 'exportfs -a'
+fi
 
 echo -n "New "
 showmount -e $VIGRID_NAS_IP
