Misc bug correction (project-lowlevel-reset with null consoles) + new command to connect to VNC: vigrid-vnctouch

diff --git a/bin-nas/rsync-Vstorage b/bin-nas/rsync-Vstorage
--- a/bin-nas/rsync-Vstorage
+++ b/bin-nas/rsync-Vstorage
@@ -10,24 +10,23 @@
 #
 #################################################################################################################################
 
-
 PROGRESS="--progress"
 #PROGRESS=""
 
 # creating dataset missing on target FS
-ZFS_LIST=`zfs list -r Vstorage -o name |tail -n+2`
+ZFS_LIST=`zfs list -o name -r Vstorage |tail -n+2`
 for i in $ZFS_LIST
 do
   TARGET=`echo $i | sed 's/Vstorage/Vstorage_BKP/'`
 
-  [ "x$PROGRESS" != "x" ] && echo "Identified dataset: $i"
+  [ "x$PROGRESS" != "x" ] && echo "Source: Identified dataset: $i"
 
-  [ "x$PROGRESS" != "x" ] && echo "  Checking for $TARGET..."
+  [ "x$PROGRESS" != "x" ] && echo "  Target: Checking for $TARGET..."
 
   CHK=`zfs list $TARGET -o name 2>/dev/null`
   if [ "x$CHK" = "x" ]
   then
-    [ "x$PROGRESS" != "x" ] && echo -n "    $TARGET dataset does not exist"
+    [ "x$PROGRESS" != "x" ] && echo -n "    Target: $TARGET dataset does not exist"
 
     if [ -d "/$TARGET" ]
     then
@@ -35,9 +34,9 @@ do
       rm -rf /$TARGET
     fi
 
-    [ "x$PROGRESS" != "x" ] && echo " creating dataset $TARGET..." && echo
+    [ "x$PROGRESS" != "x" ] && echo " Target: creating dataset $TARGET..." && echo
     zfs create $TARGET
-    [ $? -ne 0 ] && echo "ZFS create $TARGET failed !" && sleep 5
+    [ $? -ne 0 ] && echo "Target: ZFS create $TARGET failed !" && sleep 5
   fi
 done
 
@@ -49,17 +48,17 @@ for i in $ZFS_LIST
 do
   SOURCE=`echo $i | sed 's/Vstorage_BKP/Vstorage/'`
 
-  [ "x$PROGRESS" != "x" ] && echo "Identified dataset: $i"
+  [ "x$PROGRESS" != "x" ] && echo "Target: Identified dataset: $i"
 
-  [ "x$PROGRESS" != "x" ] && echo "  Checking for $SOURCE..."
+  [ "x$PROGRESS" != "x" ] && echo "  Source: Checking for $SOURCE..."
 
   CHK=`zfs list $SOURCE -o name 2>/dev/null`
   if [ "x$CHK" = "x" ]
   then
-    [ "x$PROGRESS" != "x" ] && echo "    $SOURCE dataset does not exist, destroying dataset $i..." && echo
+    [ "x$PROGRESS" != "x" ] && echo "    Source: $SOURCE dataset does not exist, destroying dataset $i..." && echo
 
     zfs destroy -r $i
-    [ $? -ne 0 ] && echo "ZFS destroy $i failed !" && sleep 5
+    [ $? -ne 0 ] && echo "Source: ZFS destroy $i failed !" && sleep 5
   fi
 done
 
@@ -71,4 +70,3 @@ rsync -r --delete --existing --ignore-existing --ignore-errors --delete-before -
 
 echo "    ...then data..."
 rsync -EAXDtogrHpav --force --numeric-ids --force $PROGRESS --inplace /Vstorage/ /Vstorage_BKP/
-
